# Generated by Django 3.2 on 2021-04-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='group_id',
            new_name='fakulcy_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_id',
            new_name='group_id',
        ),
    ]
